//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Komodo.Data;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Komodo.Core.Domain
{
    [Table("BuildInfo")]
    public partial class BuildInfo : EntityBase
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(Order = 0)]
        public int Id { get; set; }
        [Column(Order = 1)]
        public string Env { get; set; }
        [Column(Order = 2)]
        public string ProjectName { get; set; }
        [Column(Order = 3)]
        public string BuildNo { get; set; }
        [Column(Order = 4)]
        public string BuildName { get; set; }
        [ Column(Order = 5)]
        public Nullable<DateTime> BuildStartDate { get; set; }
        [Column(Order = 6)]
        public Nullable<DateTime> BuildFinishedDate { get; set; }
    }
}
